### PR TITLE
Created std/math and added TravisCI file

### PR DESCRIPTION
**Pull request by Maaarcocr**
I have created the std/math library that contains: sin, sqrt, PI and the Euler Number.

I have also added the .travis.yml file so that we can add TravisCI testing when you are comfortable with it :) 

I wanted to add a cos function but I wasn't unsure how to go about it. Should I create a zetaVM instruction or should I derive cos in plush from the sin function?

### CODE REVIEW

**Comment by maximecb** [comment]
I added a cos instruction while you weren't looking ;) Most hardware provides both sin and cos machine instructions, so it makes sense to have primitives for both.

Can you add min, max and abs functions to the math package?

**Comment by maximecb** [comment]
Also wanted to say, it's great to have your help. I just started a new job, moved to another city, and would not have had time to add FP support for a while. Now that FP support is in, we can think about using it for fun stuff like audio and graphics.

I'm going to be giving a talk about Zeta at PolyConf 2017 in July, and I'd like to have some cool stuff to show people to get them interested in the project. One possibility would be a sort of functional audio synthesis API.

Another cool idea could be to implement a mini LISP dialect for Zeta and have it interoperate with Plush. And also, I was thinking we could have language extensions in Plush. The core language is simple, but we could allow people to add things to the language by implementing their own parser extensions. This would mean you can implement your own regex syntax or template strings if you wanted, for example.

**Comment by Maaarcocr** [comment]
Thank you for this great project! It has been really cool so far being able to contribute (and fun!) 

I'll add the min, max, and abs functions soon. Just one thing: does max returns the biggest value between 2 numbers or does it return the biggest value in an array? (the same holds for min)

Next thing I will try to do is the audio API, but I have some doubts about it. I'll make an issue describing them.

On implementing a language: with a friend of mine we were thinking of writing one, I hope we actually do it. I'll let you updated about it.

The language extension seems like a really cool idea, but I'm not really sure how to go about it. 

In future I would love to try implement a Garbage Collector for zeta, even though I have no knowledge about them. I may just try and see how it goes.

Again, thank you for all of this, it's just great :)

**Comment by maximecb** [comment]
There is no support for var-arg functions for now, so let's do min and max for just two values. It's always possible to add like a functional fold operator and use that to apply min and max to arrays, but we'll worry about that later.

> Next thing I will try to do is the audio API, but I have some doubts about it. I'll make an issue describing them.

Curious to hear what you have to say.

> On implementing a language: with a friend of mine we were thinking of writing one, I hope we actually do it. I'll let you updated about it.

All languages are welcome. Right now there is only Plush running on Zeta. It would be great to have at least one other working language.

> The language extension seems like a really cool idea, but I'm not really sure how to go about it.

I have some ideas on how to go about that. I will likely implement this myself. Right now on my TODO list I have exceptions. Then I will add better parser tests, and fix some parser issues like the one you outlined with assert (ie: you can't name a function assertFP, there are other similar problems). Then once I have the Plush parser in better working order, I can implement extension mechanisms for it. This is probably a pretty cool feature to demonstrate at the conference.

> In future I would love to try implement a Garbage Collector for zeta, even though I have no knowledge about them. I may just try and see how it goes.

I'm not a GC expert either. I've implemented super-simplistic stop-the-world GCs before. If you want to implement a GC for Zeta later, I can take the time to clean up places in the runtime where a GC implementation will attach. I can also port over a number of GC tests I had written for my Higgs JIT. It's very important to test GCs well, because they are hard to debug, can cause very weird unpredictable failures.

**Comment by Maaarcocr** [comment]
I've added max, min and abs (plus some tests).

**Comment by maximecb** [comment]
I'm going to merge it and make a few changes. The math library should go into math/0, because every library is going to be versioned. That is, eventually there could be a math/1, math/2, etc with new features, but the original math/0 library will still remain available.

**Comment by maximecb** [comment]
Made the changes I wanted in this commit:
https://github.com/maximecb/zetavm/commit/9abfcaede791ed41d819b27c1b6d1ebfc5472c1a

:D

**Pull request merged**
