### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by Maaarcocr**

### CODE REVIEW

**Comment by Maaarcocr** [comment]
I was trying to test travis functionality on pull requests. I actually wanted to fork with my master branch, but it went wrong. 

(If you are interested in using travis for testing zetavm I've written the .travis.yml file to test it against clang and gcc on both linux and macOS)

**Comment by maximecb** [comment]
Yes, I think we should definitely use travis. We should have it build with both gcc and clang, and then run `make test` with one of them.

**Comment by Maaarcocr** [comment]
So, I've tested it and it seems to work. The only problem is that it has problems with testing on macOS, meaning that they have a smaller number of Mac machines, thus it waits for a very long time before actually testing on this platform. Should we just test on Linux for now?

**Comment by maximecb** [comment]
That's unfortunate. I guess we can test it on linux only for now.

**Pull request closed without merging**
