### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by marekjm**
Hi.

I noticed that you said you wanted to limit undefined behaviours to the minimum, and are generally interested in having a high-quality, working code.
Then I checked your compiler flags... and found nothing there.

So I added some to see what would happen and fixed some of them (mostly old-style casts, type mismatches [signed-unsigned compares, assigning wider integer types to narrower ones, etc.).
You also have plenty of "shadowing warnings" (because of your use of `this->member` syntax, I'd guess).

I left the `-Werror -Wfatal-errors` flags out, but I'd recommend 1) you add them to `configure.ac` once the warnings are all fixed, and 2) keeping you compiles warning-free. Saves you headaches in the long run ;-)

Good luck with the VM!

### CODE REVIEW

**Comment by maximecb** [comment]
Hi there,

Questions/comments:

1. What's [[gnu::unused]] ? I would rather not use gnu-specific extensions. I want this to compile on clang as well, and other compilers.

2. I would rather this not be removed:

-        bool unitFun,
+        bool, // unitFun (unused) 

It needs to be taken into account eventually. In general, I find wunused rather annoying. At the very least, I'm against all-warnings-as-errors being enabled if wunused is going to be enabled

3. Is it really necessary to put static on every local function definition? I thought I heard somewhere that the static keyword was being deprecated?

4. I don't like the changes wrt shadowing and class member initialization. Forcing the parameters to have a different name than the class members seems rather unnecessary.

**Comment by marekjm** [comment]
The `[[gnu::unused]]` is a GCC C++11-style attribute telling the compiler that this variable may be unused. If you don't like `-Wunused` it can be removed. Same thing with point 2.

I didn't get the memo about `static` being deprecated, but it seems it became "[undeprecated](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1012)" (is that even a word?). It also provides self-documentation with regard to what comprises your module's public interface and what is internal.

4. I don't understand why you would think it is unnecessary. I think allowing parameter and member to have the same name is risky, but we're not here to discuss opinions (we could, if you're interested) and it's your code after all so I'll rewrite those parts back to same-name policy.

As an aside, you could create a style-guide with some simple rules. From what you wrote:

- block-opening brackets on their own line
- tabs expanded to four spaces,
- variables may be left unused
- parameters and members may have the same name

Because there are warnings available for two last points compiler-warning-free-compiles junkies like me may think it would be a good idea to turn them on, while for this project it is not.

**Comment by marekjm** [comment]
I removed the `[[gnu::unused]]` attribute, and disabled unused-family warnings; restored shadowing parameters in ctros, and disabled shadow-family warnings.

Also fixed possible merge conflicts (you have changed the `-O0` to `-O3` in the meantime).

**Comment by maximecb** [comment]
Can you remove the static qualified on local functions and the remaining parameter renamings?

**Comment by marekjm** [comment]
Done.

**Comment by maximecb** [comment]
There are still multiple variable renamings, and I'm not happy with lines like this. This is fairly unreadable:

```
assert (static_cast<decltype(locals.size())>(localIdx) < locals.size());
```

I apologize but I'm going to reject the PR at this point. Your intentions are good and I do think we should probably have more warnings, but I don't like the idea of a PR with hundreds of tiny changes.  It's also problematic because I'm making changes in another branch which would conflict with this.

**Comment by marekjm** [comment]
I agree it is not the most readable code in existence, but it is a good thing - these are lines where signed integer is compared with unsigned integer, so they are "marked" appropriately as places when bugs may be lurking. Similarly to other such lines, the ugliness is there to annoy your aesthetic taste and push you to rewrite code in a way that they are not needed, or hidden in just a few places. You may, of course, think differently.

I would advise you to consider letting the compiler work for you in spotting code which may be erroneous - this is what compilers are good at, after all. I feel what you mean about "a PR with hundreds of tiny changes", and I am also not entirely happy with the form I submitted it to you, but I thought that it would be better to face some difficulties now, than be hunting for bugs later when the codebase grows in size from 8 to 20KLOC and more.

Different people, different opinions, different styles I guess. Good luck with the project.

**Pull request closed without merging**
