### PR TITLE
More functionality for floats + Bug fixes

### PR DESCRIPTION
**Pull request by Maaarcocr**
I've added comparisons operations to floats (both in zeta and plush).

I've also added conversion operations for floats-strings to zeta, but I'm not sure how you want to implement them for plush. 

I've added a new test file written in plush for floats.

### CODE REVIEW

**Comment by Maaarcocr** [comment]
I've also changed the float parsing code in plush and zeta (as you mentioned in the other PR)

**Comment by maximecb** [comment]
Very good overall. Some remarks:

1. The curly braces, the humanity!

2. The float tests seem a bit inadequate. You should be testing some of the results of arithmetic operations. To do that, write a function in tests/plush/float.pls that does something like this:

````
assertFloat = function (xVal, xExpect, errMsg)
{
    var err = xVal - xExpect;
    if (err < 0)
        err = -err;

    assert (err < 0.001, errMsg);
}
````

3. sin, cos, sqrt, I guess it's ok to keep those in runtime,pls for now, but I would eventually like to move these to a standalone math library that can be shared by multiple languages, not just plush.

**Comment by Maaarcocr** [comment]
1) I should write a linter to check my braces 😂
2) I will do this!
3) I'll try to see if I can make a standalone math library, any ideas what else should be in there? Constants like PI and Euler number? 
Also, I've read how core/io and other modules are implemented but they only expose functions, would it be possible to expose constants?

**Comment by Maaarcocr** [comment]
I noticed that I wasn't able to declare a function called assertFP. It seems like it expects a '(' straight after the word assert.

**Comment by Maaarcocr** [comment]
I just pushed 2 changes that are not relevant to this PR, but they are bug fixes.

One solves a problem with the makefile and Linux, in fact I was not able to use SDL2 at all due to the order of the flags.

The order bug fix solves issue #27. It was caused by a pointer misuse.

**Comment by maximecb** [comment]
> I noticed that I wasn't able to declare a function called assertFP. It seems like it expects a '(' straight after the word assert.

That's a bug in the parser. I will fix it once I have exceptions in.

**Comment by maximecb** [comment]
@Maaarcocr 

> I'll try to see if I can make a standalone math library, any ideas what else should be in there? Constants like PI and Euler number?

Yes, PI and E should be in there, along with sin, cos, sqrt. Also min(x,y), max(x,y), abs(x).

> Also, I've read how core/io and other modules are implemented but they only expose functions, would it be possible to expose constants?

This library should be implemented in plush, like parser.pls. You can export functions and constants by doing:

```
exports.myFunction = function() {};
exports.PI = 3.1416;
```

The plush source file for the library should be placed at packages/std/math/package (no .pls extension).

**Comment by maximecb** [comment]
@Maaarcocr 

> I should write a linter to check my braces

Maybe in a bit we can dogfood Zeta by writing the linter in Plush ;)

**Pull request merged**
